
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace PtNM_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            PicToNumbModel.ModelInput sampleData = new PicToNumbModel.ModelInput()
            {
                ImageSource = @"C:\Users\const\OneDrive\Documents\Visual Studio 2019\Projects\SWE_picturesOfNumbers\SWE_picturesOfNumbers\mnist_png.tar\mnist_png\testing\7\1326.png",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = PicToNumbModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ImageSource: {@"C:\Users\const\OneDrive\Documents\Visual Studio 2019\Projects\SWE_picturesOfNumbers\SWE_picturesOfNumbers\mnist_png.tar\mnist_png\training\0\1.png"}");

            //PUSH THIS SHIT PLSSSSSSS

            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
